language: cpp
compiler: gcc
before_install:
    # GCC 4.9 needed for more complete c++11 support
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
    - sudo apt-get update -qq
install:
    # GCC
    - sudo apt-get install -y g++-4.9
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
    # SDL
    - sudo apt-get install -y libsdl2 libsdl2-dev
    # FFmpeg
    - sudo apt-get install -y yasm
    - mkdir tmp && pushd tmp
    - wget http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
    - tar xvf ffmpeg-snapshot.tar.bz2
    - cd ffmpeg
    - ./configure --prefix=/usr --enable-shared --disable-static
      --disable-programs --disable-doc --disable-avdevice --disable-postproc
      --disable-avfilter
    - make
    - sudo make install
    - make distclean
    - popd && rm -rf tmp
script: make
