#ifndef _POCKETSPHINXJS_CONFIG_H_
#define _POCKETSPHINXJS_CONFIG_H_

#define HAVE_CONFIG_H 1
#define HMM_FOLDERS "rm1_200"
/* #undef DICT_FILES */
/* #undef LM_FILES */

#endif /* _POCKETSPHINXJS_CONFIG_H_ */
