# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_FREEBSD "")
SET(CPACK_BINARY_IFW "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_PRODUCTBUILD "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TXZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_BUILD_SOURCE_DIRS "/home/netpipe/Desktop/EMScripten-AddonBundle/emscripten-projects/media/fluidsynth-emscripten;/home/netpipe/Desktop/EMScripten-AddonBundle/emscripten-projects/media/fluidsynth-emscripten")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "STGZ;TGZ;TBZ2;ZIP")
SET(CPACK_INSTALL_CMAKE_PROJECTS "/home/netpipe/Desktop/EMScripten-AddonBundle/emscripten-projects/media/fluidsynth-emscripten;FluidSynth;ALL;/")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "/home/netpipe/Desktop/EMScripten-AddonBundle/emscripten-projects/media/fluidsynth-emscripten/cmake_admin;/run/media/netpipe/df7f53ef-2a98-4562-a498-7da578dab660/Dev/libs/Scripting/emsdk/upstream/emscripten/cmake/Modules")
SET(CPACK_NSIS_DISPLAY_NAME "fluidsynth 2.0.2")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "fluidsynth 2.0.2")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/netpipe/Desktop/EMScripten-AddonBundle/emscripten-projects/media/fluidsynth-emscripten/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/home/netpipe/Desktop/EMScripten-AddonBundle/emscripten-projects/media/fluidsynth-emscripten/README.md")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "FluidSynth real-time synthesizer")
SET(CPACK_PACKAGE_EXECUTABLES "fluidsynth;FluidSynth CLI")
SET(CPACK_PACKAGE_FILE_NAME "fluidsynth-2.0.2-Emscripten")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "fluidsynth 2.0.2")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "fluidsynth 2.0.2")
SET(CPACK_PACKAGE_NAME "fluidsynth")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "fluidsynth.org")
SET(CPACK_PACKAGE_VERSION "2.0.2")
SET(CPACK_PACKAGE_VERSION_MAJOR "2")
SET(CPACK_PACKAGE_VERSION_MINOR "0")
SET(CPACK_PACKAGE_VERSION_PATCH "2")
SET(CPACK_RESOURCE_FILE_LICENSE "/home/netpipe/Desktop/EMScripten-AddonBundle/emscripten-projects/media/fluidsynth-emscripten/LICENSE")
SET(CPACK_RESOURCE_FILE_README "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ;TBZ2;ZIP")
SET(CPACK_SOURCE_IGNORE_FILES "/.svn/;/build/;~$;.cproject;.project;/.settings/;")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/netpipe/Desktop/EMScripten-AddonBundle/emscripten-projects/media/fluidsynth-emscripten/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "fluidsynth-2.0.2")
SET(CPACK_SOURCE_RPM "")
SET(CPACK_SOURCE_STRIP_FILES "OFF")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TXZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_STRIP_FILES "ON")
SET(CPACK_SYSTEM_NAME "Emscripten")
SET(CPACK_TOPLEVEL_TAG "Emscripten")
SET(CPACK_WIX_SIZEOF_VOID_P "4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/netpipe/Desktop/EMScripten-AddonBundle/emscripten-projects/media/fluidsynth-emscripten/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
