 ###########################################################################
 ## This file is created automatically from your config file.
 ## Do not hand edit.
 ## Created:Mon Oct 6 14:02:55 MDT 2014
 ###########################################################################

MOD_DESC_NATIVE_AUDIO=Native audio module for your system
INCLUDE_NATIVE_AUDIO=1
include $(TOP)/config/modules/editline.mak
include $(TOP)/siod/siod.mak
include $(TOP)/stats/wagon/wagon.mak
include $(TOP)/grammar/scfg/scfg.mak
include $(TOP)/grammar/wfst/wfst.mak
include $(TOP)/stats/ols.mak
include $(TOP)/rxp/rxp.mak
include $(TOP)/config/modules/linux16_audio.mak
